spring:
  application:
    name: order_server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.122.44.127:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
eureka:
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
env:
  test67


girl:
  name: "alicia"
  age: 567
  school: "haha university"
