spring:
  application:
    name: order_server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.122.44.127:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  rabbitmq:
    host: 10.122.44.127
    port: 5672
    username: guest
    password: guest
  stream:
    bindings:
      MessageOut:
        destination: stream-demo
      MessageIn:
        destination: stream-demo
eureka:
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/,http://server2:8762/eureka/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
env:
  test678901234567


girl:
  name: "alicia"
  age: 567867
  school: "haha university"
