spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.122.44.127:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  rabbitmq:
    host: 10.122.44.127
    password: guest
    port: 5672
    username: guest
  jpa:
    show-sql: true

